#!/usr/bin/env php
<?php

require 'src/Lz4.php';
require 'src/MalformedLz4DataException.php';
require 'src/Lz4/Frame.php';
require 'src/Lz4/DataBlock.php';

function trace(...$a) { fputs(STDERR, implode($a) .PHP_EOL); }
function td(...$a) { foreach ($a as $v) var_dump($v); die('td()'); }
function tp(...$a) { foreach ($a as $v) var_dump($v); echo 'tp()', PHP_EOL; }

$a = [];
foreach (array_slice($argv, 1) as $filePN)
	$a[] = fopen($filePN, 'rb');
if (empty($a))
	$a = [ STDIN ];
foreach ($a as $hin)
	echo dexen\mulib\Lz4::decompress(stream_get_contents($hin));
